### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by VMARCV** [goleh/bitcoin-ticker#3]
if (!client.connect(restApiHost, 443))

Always fails at this point, cannot connect to binance, don't know why.

**Comment by spareleg** [comment]
Have you checked if you have connection with binance API from your IP on another device? Try to open the https://api.binance.com in the browser on any device connected to same router

**Comment by VMARCV** [comment]
I launch api.binance.com
On the top of the browser appears Test Ok, and an empty page.

**Comment by VMARCV** [comment]
I launch api.binance.com
On the top of the browser appears Test Ok, and an empty page.

*Sorry, I closed by error.

**Comment by spareleg** [comment]
It also may be caused by having different versions of packages than mentioned in the comments at the beginning of the script. I also had an error at that point when I used latest versions for all installed packages.

**Comment by VMARCV** [comment]
Versions are ok, probably is my board version.
I'll check again.

Thanks
