### ISSUE TITLE
"Internet connection lost. Check the Wi-Fi source." Error message

### ISSUE THREAD

**Issue by guiguijke** [goleh/bitcoin-ticker#4]
Hello , 
I've built your bitcoin ticker, and I'm working on it at this moment.
I used the libs exactly on the versions you are mentionning but it wasn't working, I had this error msg after getting the time from internet.

Solution : add "client.setInsecure();" after line 214 WiFiClientSecure client;

**Comment by frittna** [comment]
hi, well, i admit i have no clue why this message comes as all my 3 identical devices are working without that line. Maybe there was a problem or changing in the binance api. I have only noticed a lost connection for some minutes some days ago, but we are in the middle of a crazy cryüto bull run so maybe it was just a server problem?.. have you tried it without this line any time later?

**Comment by guiguijke** [comment]
Hello,

I tried again, but without this line, my device is just black, showing
nothing at all.

Anyway, did you find a way to have the last price + last cande redrawn
between each timeframe change ?

Regards

**Comment by spareleg** [comment]
Hi,
Last candle is always redrawn on new price that comes through websockets, and if that price is higher than chart high or lower than chart low then all candles are redrawn.
All my devices work without .setInsecure(), maybe Binance filters secure connections somehow or your router.

**Comment by guiguijke** [comment]
Thanks for your answer.
For an unknown reason, on my side , the price is updated only when
timeframe is changing. There are no changes in between...
Regards

**Comment by spareleg** [comment]
Maybe it's the same problem as with REST API connection and you need to switch websockets connection to insecure mode too

**Comment by guiguijke** [comment]
Do you have any idea on how to do this ? This is over my arduino's coding
skills ...
Thanks a lot.

**Comment by spareleg** [comment]
First that I would try is to replace webSocket.beginSSL with webSocket.begin in both places

**Comment by spareleg** [comment]
But I'm not sure if Binance supports not secure websockets connections

**Comment by guiguijke** [comment]
Well , 
1-> if I don't put client.setInsecure(); for the api -> the board reboots , and no price / candle is shown
2-> if I put client.setInsecure(); for the api -> price + candles are drawing on the screen , then error msg " WS Disconnected" .  In both cases webSocket.beginSSL or webSocket.begin
---> weirdest thing is that for a timeframe update, everything works well ...

**Comment by spareleg** [comment]
https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md
Seems like Binance only supports wss (secure ws), and the reason secure ws doesn't work is likely the same as why secure rest api doesn't work. Can you test if it works with another router?
